/**
 * ============LICENSE_START=======================================================
 * org.onap.aai
 * ================================================================================
 * Copyright © 2025 Deutsche Telekom.
 * ================================================================================
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * ============LICENSE_END=========================================================
 */

package org.onap.aai.schemagen.genxsd;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.onap.aai.edges.EdgeIngestor;
import org.onap.aai.nodes.NodeIngestor;
import org.onap.aai.schemagen.SwaggerGenerationConfiguration;
import org.onap.aai.schemagen.testutils.TestUtilConfigTranslatorForCharacterization;
import org.onap.aai.setup.SchemaConfigVersions;
import org.onap.aai.setup.SchemaLocationsBean;
import org.onap.aai.setup.SchemaVersion;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.TestPropertySource;
import org.springframework.test.context.junit.jupiter.SpringJUnitConfig;

/**
 * Characterization (approval) test that pins the full swagger/YAML generation output for a large,
 * branch-rich OXM input (the ~92-type v13 fixture set), rather than the 6-type v11 input that the
 * hand-built golden in {@link YAMLfromOXMTest} covers. This is the regression net for the phase-2
 * refactor of {@code processJavaTypeElementSwagger} and the static accumulator maps: any change
 * that alters generated bytes, the set of registered relationship paths, or their ordering fails
 * here.
 *
 * <p>
 * The expected YAML lives in a committed golden resource; see {@link GoldenFile} for how to
 * regenerate it after an intentional output change.
 */
@SpringJUnitConfig(
    classes = {SchemaConfigVersions.class, SchemaLocationsBean.class,
        TestUtilConfigTranslatorForCharacterization.class, EdgeIngestor.class, NodeIngestor.class,
        SwaggerGenerationConfiguration.class})
@TestPropertySource(properties = {"schema.uri.base.path = /aai", "schema.xsd.maxoccurs = 5000"})
public class SwaggerGenerationCharacterizationTest {

    private static final SchemaVersion VERSION = new SchemaVersion("v13");

    @Autowired
    YAMLfromOXM yamlFromOxm;

    @Autowired
    GenerationContext generationContext;

    @BeforeEach
    public void resetSharedState() {
        // the context bean is a run-scoped singleton shared across test methods; start each clean
        generationContext.clear();
    }

    @Test
    public void yamlOutputMatchesGolden() throws Exception {
        yamlFromOxm.setVersion(VERSION);

        GoldenFile.assertMatches("aai_swagger_v13.golden.yaml", yamlFromOxm.process());
    }

    @Test
    public void relationshipPathsAreRegistered() throws Exception {
        yamlFromOxm.setVersion(VERSION);
        yamlFromOxm.process();

        // PUT on a .../relationship-list/relationship endpoint registers into putRelationPaths;
        // this is the map + ordering behaviour the phase-2 static-maps->context change rewrites.
        assertFalse(generationContext.getPutRelationPaths().isEmpty(),
            "expected relationship PUT paths to be registered for the v13 fixture set");
        assertTrue(generationContext.getDeletePaths().size() > generationContext
            .getPutRelationPaths().size(),
            "expected more delete object paths than relationship paths");

        // every registered relationship op id must map to a path that is a relationship endpoint
        generationContext.getPutRelationPaths()
            .forEach((opId, path) -> assertTrue(path.endsWith("/relationship-list/relationship"),
                "registered non-relationship path for " + opId + ": " + path));
    }
}
