@startuml
title v13 Active and Available Inventory EdgeRule Relationships
"allotted-resource" -- "allotted-resource" : BindsTo >
"allotted-resource" -- "generic-vnf" : PartOf >
"allotted-resource" -- "instance-group" : MemberOf >
"allotted-resource" -- "l3-network" : PartOf >
"allotted-resource" -- "l-interface" : Uses >
"allotted-resource" -- "model-ver" : IsA >
"allotted-resource" -- "network-policy" : Uses >
"allotted-resource" -- "vlan" : PartOf >
"availability-zone" -- "complex" : LocatedIn >
"availability-zone" -- "service-capability" : AppliesTo >
"cloud-region" -- "complex" : LocatedIn >
"cloud-region" -- "instance-group" : Uses >
"cloud-region" -- "l3-network" : Uses >
"cloud-region" -- "zone" : LocatedIn >
"collection" -- "model-ver" : IsA >
"complex" -- "l3-network" : Uses >
"configuration" -- "allotted-resource" : Uses >
"configuration" -- "configuration" : BindsTo >
"configuration" -- "l3-network" : PartOf >
"configuration" -- "l-interface" : AppliesTo >
"configuration" -- "logical-link" : Uses >
"configuration" -- "model-ver" : IsA >
"configuration" -- "pnf" : AppliesTo >
"configuration" -- "vpn-binding" : Uses >
"connector" -- "model-ver" : IsA >
"connector" -- "virtual-data-center" : LocatedIn >
"ctag-pool" -- "availability-zone" : AppliesTo >
"dvs-switch" -- "availability-zone" : AppliesTo >
"esr-thirdparty-sdnc" -- "pnf" : AppliesTo >
"forwarder" -- "configuration" : Uses >
"forwarder" -- "generic-vnf" : AppliesTo >
"forwarder" -- "lag-interface" : ForwardsTo >
"forwarder" -- "l-interface" : ForwardsTo >
"forwarder" -- "p-interface" : ForwardsTo >
"forwarding-path" -- "configuration" : Uses >
"forwarding-path" -- "service-instance" : AppliesTo >
"generic-vnf" -- "availability-zone" : Uses >
"generic-vnf" -- "complex" : LocatedIn >
"generic-vnf" -- "configuration" : Uses >
"generic-vnf" -- "ctag-pool" : Uses >
"generic-vnf" -- "instance-group" : MemberOf >
"generic-vnf" -- "ipsec-configuration" : Uses >
"generic-vnf" -- "l3-network" : Uses >
"generic-vnf" -- "model-ver" : IsA >
"generic-vnf" -- "nos-server" : HostedOn >
"generic-vnf" -- "pnf" : HostedOn >
"generic-vnf" -- "pserver" : HostedOn >
"generic-vnf" -- "virtual-data-center" : LocatedIn >
"generic-vnf" -- "vnf-image" : Uses >
"generic-vnf" -- "volume-group" : DependsOn >
"generic-vnf" -- "vserver" : HostedOn >
"instance-group" -- "model" : Targets >
"instance-group" -- "model-ver" : IsA >
"l3-interface-ipv4-address-list" -- "instance-group" : MemberOf >
"l3-interface-ipv4-address-list" -- "l3-network" : MemberOf >
"l3-interface-ipv4-address-list" -- "subnet" : MemberOf >
"l3-interface-ipv6-address-list" -- "instance-group" : MemberOf >
"l3-interface-ipv6-address-list" -- "l3-network" : MemberOf >
"l3-interface-ipv6-address-list" -- "subnet" : MemberOf >
"l3-network" -- "instance-group" : MemberOf >
"l3-network" -- "model-ver" : IsA >
"l3-network" -- "network-policy" : Uses >
"l3-network" -- "route-table-reference" : Uses >
"l3-network" -- "vpn-binding" : Uses >
"lag-interface" -- "lag-link" : LinksTo >
"lag-interface" -- "l-interface" : Uses >
"lag-interface" -- "logical-link" : Uses >
"lag-interface" -- "p-interface" : Uses >
"lag-interface" -- "pnf" : BindsTo >
"lag-interface" -- "pserver" : BindsTo >
"lag-interface" -- "vpls-pe" : BindsTo >
"line-of-business" -- "generic-vnf" : Uses >
"l-interface" -- "instance-group" : MemberOf >
"l-interface" -- "logical-link" : LinksTo >
"l-interface" -- "p-interface" : BindsTo >
"l-interface" -- "vserver" : BindsTo >
"logical-link" -- "cloud-region" : LocatedIn >
"logical-link" -- "generic-vnf" : BridgedTo >
"logical-link" -- "lag-link" : Uses >
"logical-link" -- "l-interface" : Destination >
"logical-link" -- "l-interface" : Source >
"logical-link" -- "logical-link" : Uses >
"logical-link" -- "model-ver" : IsA >
"logical-link" -- "pnf" : BridgedTo >
"logical-link" -- "pserver" : BridgedTo >
"logical-link" -- "virtual-data-center" : LocatedIn >
"logical-link" -- "vpn-binding" : Uses >
"model-element" -- "model-ver" : IsA >
"named-query" -- "model" : AppliesTo >
"named-query-element" -- "model" : IsA >
"network-profile" -- "generic-vnf" : AppliesTo >
"nos-server" -- "pserver" : HostedOn >
"oam-network" -- "complex" : AppliesTo >
"oam-network" -- "service-capability" : AppliesTo >
"operational-environment" -- "operational-environment" : Uses >
"p-interface" -- "logical-link" : LinksTo >
"p-interface" -- "physical-link" : LinksTo >
"p-interface" -- "pnf" : BindsTo >
"p-interface" -- "pserver" : BindsTo >
"p-interface" -- "vpls-pe" : BindsTo >
"platform" -- "generic-vnf" : Uses >
"pnf" -- "complex" : LocatedIn >
"pnf" -- "instance-group" : MemberOf >
"pnf" -- "model-ver" : IsA >
"pnf" -- "zone" : LocatedIn >
"project" -- "service-instance" : Uses >
"pserver" -- "availability-zone" : MemberOf >
"pserver" -- "cloud-region" : LocatedIn >
"pserver" -- "complex" : LocatedIn >
"pserver" -- "group-assignment" : MemberOf >
"pserver" -- "zone" : LocatedIn >
"service-instance" -- "allotted-resource" : Uses >
"service-instance" -- "collection" : ComposedOf >
"service-instance" -- "configuration" : ComposedOf >
"service-instance" -- "configuration" : Uses >
"service-instance" -- "connector" : Uses >
"service-instance" -- "ctag-assignment" : Uses >
"service-instance" -- "cvlan-tag" : ComposedOf >
"service-instance" -- "generic-vnf" : ComposedOf >
"service-instance" -- "instance-group" : MemberOf >
"service-instance" -- "l3-network" : ComposedOf >
"service-instance" -- "logical-link" : Uses >
"service-instance" -- "model-ver" : IsA >
"service-instance" -- "pnf" : ComposedOf >
"service-instance" -- "service-instance" : ComposedOf >
"service-instance" -- "vce" : ComposedOf >
"service-instance" -- "vlan" : ComposedOf >
"service-instance" -- "zone" : LocatedIn >
"service-subscription" -- "tenant" : Uses >
"site-pair-set" -- "generic-vnf" : AppliesTo >
"sriov-vf" -- "sriov-pf" : Uses >
"tenant" -- "group-assignment" : MemberOf >
"tenant" -- "l3-network" : Uses >
"tenant" -- "volume-group" : DependsOn >
"vce" -- "availability-zone" : Uses >
"vce" -- "complex" : LocatedIn >
"vce" -- "vserver" : HostedOn >
"vf-module" -- "l3-network" : DependsOn >
"vf-module" -- "model-ver" : IsA >
"vf-module" -- "vnfc" : Uses >
"vf-module" -- "volume-group" : Uses >
"vf-module" -- "vserver" : Uses >
"vip-ipv4-address-list" -- "instance-group" : MemberOf >
"vip-ipv4-address-list" -- "subnet" : MemberOf >
"vip-ipv6-address-list" -- "instance-group" : MemberOf >
"vip-ipv6-address-list" -- "subnet" : MemberOf >
"vlan" -- "l-interface" : LinksTo >
"vlan" -- "logical-link" : Uses >
"vlan" -- "multicast-configuration" : Uses >
"vnfc" -- "instance-group" : MemberOf >
"vnfc" -- "model-ver" : IsA >
"vnfc" -- "vip-ipv4-address-list" : Uses >
"vnfc" -- "vip-ipv6-address-list" : Uses >
"vnfc" -- "vserver" : HostedOn >
"volume-group" -- "complex" : LocatedIn >
"vpls-pe" -- "complex" : LocatedIn >
"vpls-pe" -- "ctag-pool" : Uses >
"vpn-binding" -- "customer" : Uses >
"vserver" -- "flavor" : Uses >
"vserver" -- "image" : Uses >
"vserver" -- "pserver" : HostedOn >
"vserver" -- "snapshot" : Uses >
"vserver" -- "volume" : AttachesTo >
"zone" -- "complex" : LocatedIn >
@enduml
